zenangst/Blueprints

Blueprints.xcodeproj/project.pbxproj, Sources/Shared/BlueprintLayout.swift, Sources/Shared/BlueprintSupplementaryKind.swift, Sources/Shared/HorizontalBlueprintLayout.swift, Sources/Shared/VerticalBlueprintLayout.swift, Sources/macOS/Extensions/BlueprintLayout+macOS.swift, Sources/macOS/Extensions/NSCollectionView+Extensions.swift, Tests/Shared/HorizontalBlueprintLayoutTests.swift, Tests/Shared/VerticalBlueprintLayoutTests.swift, Tests/macOS/Helper.swift
Implements initial support for sticky header and footer support.
=> Initial implementation to add header & footer support

Blueprints.podspec, Sources/Shared/Mosaic/VerticalMosaicBlueprintLayout.swift, Tests/Shared/VerticalMosaicBlueprintLayoutTests.swift
This PR aims to improve item sizing in the mosaic layout when using spacing and insets.
=> Improve mosaic layout

Blueprints.podspec, Blueprints.xcodeproj/project.pbxproj, README.md, Sources/Shared/Core/BlueprintLayout.swift, Sources/Shared/Core/BlueprintLayoutAnimation.swift, Sources/Shared/Core/BlueprintLayoutAnimator+Extensions.swift, Sources/Shared/Core/BlueprintLayoutAnimator.swift, Sources/Shared/Core/DefaultLayoutAnimator.swift, Sources/Shared/Core/HorizontalBlueprintLayout.swift, Sources/Shared/Core/VerticalBlueprintLayout.swift, Sources/Shared/Mosaic/MosaicBlueprintPatternController.swift, Sources/Shared/Mosaic/MosaicLayoutAttributes.swift, Sources/Shared/Mosaic/MosaicPattern.swift, Sources/Shared/Mosaic/VerticalMosaicBlueprintLayout.swift, Sources/Shared/Waterfall/VerticalWaterfallBlueprintLayout.swift, Tests/Shared/Blueprints-iOS-Tests-Bridging-Header.h, Tests/Shared/Blueprints-macOS-Tests-Bridging-Header.h, Tests/Shared/Blueprints-tvOS-Tests-Bridging-Header.h, Tests/iOS+tvOS/iOStvOSObjectiveCSupportTests.m, Tests/macOS/macOSObjectiveCSupportTests.m
This PR refactors the layouts to make them available in Objective-C-land.
=> Refactor project classes to add support for Objective-C

Blueprints.xcodeproj/xcshareddata/xcschemes/Blueprints-iOS.xcscheme, Sources/Shared/Mosaic/VerticalMosaicBlueprintLayout.swift, Tests/Shared/VerticalMosaicBlueprintLayoutTests.swift
This PR aims to solve rendering issues with the mosaic layout #30 
tl;dr
Fixes #30
=> Fix layout bug in mosaic layout

Blueprints.podspec, Sources/macOS/Extensions/BlueprintLayout+macOS.swift
Dont modify the alpha value if it starts hidden
=> Improve using alpha values on macOS

Blueprints.podspec, Sources/Shared/Core/BlueprintLayout.swift
=> Index path invalidated during code execution

Sources/Shared/Core/VerticalBlueprintLayout.swift
=> Set sectionMaxY for when only one item is displayed in a section

Example-iOS/Scenes/LayoutExampleSceneViewController+HorizontalBlueprintLayout.swift, Example-iOS/Scenes/LayoutExampleSceneViewController+VerticalBlueprintLayout.swift, Sources/Shared/Core/HorizontalBlueprintLayout.swift, Sources/Shared/Core/VerticalBlueprintLayout.swift, Tests/Shared/HorizontalBlueprintLayoutTests.swift, Tests/Shared/PeformanceTests.swift, Tests/Shared/VerticalBlueprintLayoutTests.swift, Tests/iOS+tvOS/Helper.swift, Tests/iOS+tvOS/iOStvOSObjectiveCSupportTests.m, Tests/macOS/Helper.swift, Tests/macOS/macOSObjectiveCSupportTests.m
Fixes https://github.com/zenangst/Blueprints/issues/43
=> Add convenience init to avoid itemSize and itemsPerRow confusion

Example-iOS/Scenes/LayoutExampleSceneViewController+VerticalMosaicBlueprintLayout.swift, Sources/Shared/Mosaic/VerticalMosaicBlueprintLayout.swift, Tests/iOS+tvOS/iOStvOSObjectiveCSupportTests.m
Implements basic header support for mosaic layout.
There is more work to be done here in the future.
=> Add basic header support for mosiac layout

Sources/Shared/Core/BlueprintLayout.swift, Sources/Shared/Core/HorizontalBlueprintLayout.swift, Sources/macOS/Extensions/BlueprintLayout+macOS.swift
=> Resolve issues for incorrect header sizes

Example-OSX/Scenes/LayoutExampleSceneViewController+VerticalMosaicBlueprintLayout.swift, Example-iOS/Scenes/LayoutExampleSceneViewController+VerticalMosaicBlueprintLayout.swift, Sources/Shared/Mosaic/VerticalMosaicBlueprintLayout.swift
Following on from #75 lets add basic support for footers 😃
=> Basic support for footers in the mosaic layout

README.md
Remove waterfall from example and add dynamic sizing preview.
=> Update previews in Readme

Sources/macOS/Extensions/BlueprintLayout+macOS.swift
When switching back from horizontal to vertical the width needs to be adjusted to resolve the issue.
=> Also adjust the width of the frame.

Example-iOS/Common/Components/TitleCollectionReusableView.xib
=> Update constraints to fix #98

Blueprints.podspec, Sources/macOS/Extensions/BlueprintLayout+macOS.swift
- 💻 Fixes content issue bug on macOS
=> Use super class content size height instead of hardcoded value

Blueprints.podspec, Sources/Shared/Core/BlueprintLayout.swift, Sources/macOS/Extensions/BlueprintLayout+macOS.swift
The fix had negative side-effects.
=> Revert last fix content size fix

README.md
Set height of preview to `540` for fit screen. See Preview:
**Before:**
**After:**
=> Fix preview size

Blueprints.podspec, Blueprints.xcodeproj/project.pbxproj, Sources/Shared/Core/VerticalBlueprintLayout.swift, Sources/Shared/Mosaic/VerticalMosaicBlueprintLayout.swift
Fixes #110 the offset was not included when footers where not been used.
=> Fix sectionInset.bottom when footers are not in use

Blueprints.podspec, Sources/Shared/Core/HorizontalBlueprintLayout.swift, Sources/Shared/Core/VerticalBlueprintLayout.swift
This stops the index out of bounds exception
=> Add empty layoutAttribute when there are no items in a section

Blueprints.podspec, Sources/Shared/Mosaic/VerticalMosaicBlueprintLayout.swift
When you forget to update all the layouts.. oops.
=> Including the origional fix on the mosaic layout.

Blueprints.podspec, Blueprints.xcodeproj/project.pbxproj, Sources/Shared/Core/BlueprintLayout.swift, Sources/Shared/Core/HorizontalBlueprintLayout.swift, Sources/Shared/Core/VerticalBlueprintLayout.swift, Sources/Shared/Mosaic/VerticalMosaicBlueprintLayout.swift, Tests/Shared/HorizontalBlueprintLayoutDelegateTests.swift, Tests/Shared/VerticalBlueprintLayoutDelegateTests.swift, Tests/Shared/VerticalMosaicBlueprintLayoutDelegateTests.swift, Tests/Shared/VerticalMosaicBlueprintLayoutTests.swift, Tests/iOS+tvOS/Helper.swift, Tests/iOS+tvOS/Mocks.swift, Tests/iOS+tvOS/VerticalBlueprintLayoutTests+iOS+tvOS.swift, Tests/macOS/Mocks.swift
This implements the delegate methods for both minimumInteritemSpacing and minimumLineSpacing delegates.
=> Feature implement cell spacing delegate methods

Blueprints.podspec, Sources/Shared/Core/VerticalBlueprintLayout.swift, Sources/Shared/Mosaic/VerticalMosaicBlueprintLayout.swift
=> Fix negative index

Sources/Shared/Core/BlueprintLayout.swift
Remove the use of filter and sorting to improve the performance of `prepare`
=> Refactor createCache(with:) method

Blueprints.podspec, Sources/Shared/Core/BlueprintLayout.swift
- Use enclosing scroll view size to calculate width instead of the collection view
=> Fix size bug on macOS
