zenangst/Blueprints

- .travis.yml
- Blueprints.xcodeproj/project.pbxproj
- Sources/Shared/BlueprintLayout.swift
- Tests/Shared/HorizontalBlueprintLayoutTests.swift
- Tests/Shared/VerticalBlueprintLayoutTests.swift
- Tests/iOS+tvOS/HorizontalBlueprintLayoutTests+iOS+tvOS.swift
- Tests/iOS+tvOS/VerticalBlueprintLayoutTests+iOS+tvOS.swift
- Tests/macOS/HorizontalBlueprintLayoutTests+macOS.swift
- Tests/macOS/VerticalBlueprintLayoutTests+macOS.swift
On macOS, the collection view is the document view of a scroll view, to get proper dequeuing we need to resolve the scroll views rectangle instead of the rectangle that is passed to the collection view layout.
This way we make sure that we never allocate more items than necessary.
> Refactor layoutAttributesForElements to do proper dequeing

- Sources/Shared/BlueprintLayout.swift
- Sources/Shared/VerticalBlueprintLayout.swift
- Sources/iOS+tvOS/Extensions/UICollectionView+Extensions.swift
- Sources/macOS/Extensions/NSCollectionView+Extensions.swift
The collection views frame can exceed the view bounds which will cause the headers to render incorrectly. Now the width of the headers & footers use the documents visible rectangle of the scroll view instead.
> Fix UI glitch with sticky header & footers on macOS

- Sources/Shared/BlueprintLayout.swift
- Sources/Shared/HorizontalBlueprintLayout.swift
- Sources/Shared/VerticalBlueprintLayout.swift
This adds `estimatedItemSize` to init methods on the Blueprints layouts.
It will also resolve the height from the  `CollectionViewFlowLayoutDelegate` when using calculated item widths.
> Add estimatedItemSize to init methods & improve delegate usage.

- Sources/Shared/BlueprintLayout.swift
- Tests/macOS/HorizontalBlueprintLayoutTests+macOS.swift
- Tests/macOS/VerticalBlueprintLayoutTests+macOS.swift
- Scoping the rectangle to the scroll view will have an impact on scrolling performance, the rectangle that is passed into `layoutAttributesForElements` is larger than the viewport in macOS by design, and we should refrain from fighting the system as it could lead to undesired and unexpected behavior.
- Remove implementation for shouldInvalidateLayout
> Remove mac os optimization

- Sources/Shared/HorizontalBlueprintLayout.swift
Fixes issue with adding header and footer heights to empty layouts.
> Only add header and footer height if content size height is more than zero

- Sources/Shared/BlueprintLayout.swift
Constrains width to the collection view's superview. 
Fixes sizing bug when using span on horizontal layouts.
> Constraint width to superview

- Sources/Shared/Core/BlueprintLayout.swift
- Sources/Shared/Core/HorizontalBlueprintLayout.swift
- Sources/Shared/Core/VerticalBlueprintLayout.swift
- Sources/Shared/Mosaic/VerticalMosaicBlueprintLayout.swift
- Sources/Shared/Waterfall/VerticalWaterfallBlueprintLayout.swift
Each layout will now call `createCache` in their `prepare` methods. This reduces some `compactMap` operations in methods that need performance.
> Refactor caching of layout attributes

- Blueprints.podspec
- Blueprints.xcodeproj/project.pbxproj
- Sources/Shared/Core/BlueprintLayout.swift
- Tests/Shared/PeformanceTests.swift
- Tests/iOS+tvOS/HorizontalBlueprintLayoutTests+iOS+tvOS.swift
- Tests/iOS+tvOS/VerticalBlueprintLayoutTests+iOS+tvOS.swift
- Tests/macOS/HorizontalBlueprintLayoutTests+macOS.swift
This PR improves how the binary search is implemented.
It uses `intersects` for matching the closest valid layout attribute instead of checking max values against min values on the rectangle.
If there are no matches using the binary search algorithm, `intersects` will be used as a fallback.
> Improve binary search

- Blueprints.podspec
- Sources/Shared/Core/BlueprintLayout.swift
- Sources/iOS+tvOS/Extensions/BlueprintLayout+iOS+tvOS.swift
- Sources/iOS+tvOS/Extensions/BlueprintLayoutAnimator+iOS+tvOS.swift
Remove isUpdating optimization which led to crashes when reloading collection views. The occured because the optimization outed out from returning anything other than `nil` when and update is happening. Internally this caused the collection view to throw an exception when updating a collection view with mutliple inserts and deletions.
Similar to this issue here: https://github.com/ra1028/DifferenceKit/issues/13
> Fix crash when reloading collection view

- Sources/Shared/Core/BlueprintLayout.swift
- Sources/iOS+tvOS/Extensions/BlueprintLayout+iOS+tvOS.swift
- Sources/macOS/Extensions/BlueprintLayout+macOS.swift
I have had to add a check to ensure that they are cachedItems/attributes before checking the indexPath.section < cachedItems/attributes.count.
I have observed a case where the indexPath get's invalidated, this can be seen when you delete a section with a supplementary view within batch updates. However I am not sure at what point this becomes an empty index, it shouldn't occur! (So it may be possible that this will still fail) I have included the same check throughout just to air on the side of caution but I have only seen this happen for the supplementary views at this time.
> #40 invalidated layout attributes fix

- Sources/Shared/Core/VerticalBlueprintLayout.swift
Use the sectionMaxY variable instead of nextY to fix rendering issues when using cells with dynamic height.
> Use sectionMaxY instead of nextY

- Blueprints.podspec
- Sources/Shared/Core/BinarySearch.swift
- Sources/Shared/Core/BlueprintLayout.swift
When using multiple items per row with dynamic height, the binary search can cause UI glitches where certain items simply disappear after a certain content offset. To fix this issue, the `findElements` method can now pad the results that it finds. The itemsPerRow is used for padding. What padding means in this context is the number of extra items that should be allowed to exist even if they don't meet the search criteria. That way we can capture all views that are on the same row even if they have different y,x coordinates. In a real-world scenario, the number of padded items should never exceed four or five, tops.
> Add padding to BinarySearch.findElements

- README.md
- Sources/Shared/Mosaic/VerticalMosaicBlueprintLayout.swift
- Tests/iOS+tvOS/iOStvOSObjectiveCSupportTests.m
This PR changes the initializer of the Mosaic layout to only include a pattern height instead of an item size. The width of the item is never used so this change is motivated by removing the confusion that it might be used. The new label is called `patternHeight`.
Reference: https://github.com/zenangst/Blueprints/issues/43
> Improve mosaic blueprint initializer

- .travis.yml
- Example-iOS/Scenes/LayoutExampleSceneViewController+VerticalMosaicBlueprintLayout.swift
To avoid breaking the example project when changing the public API (or other things), Travis will now build the example project just to see that everything compiles.
It also fixes the example project that was broken (because I forgot to update it) :trollface:
> Build example on travis

- Example-iOS/AppDelegate.swift
- Example-iOS/Scenes/LayoutExampleSceneViewController+VerticalMosaicBlueprintLayout.swift
- Sources/Shared/Core/HorizontalBlueprintLayout.swift
- Sources/Shared/Core/VerticalBlueprintLayout.swift
- Fix crash by not calling layoutIfNeeded
- Load injection bundle for faster debugging
- Improve `shouldInvalidateLayout` function in vertical layout
- Add shouldInvalidateLayout to HorizontalBlueprintLayout
> Patch sticky headers branch

- Sources/macOS/Extensions/NSCollectionView+Extensions.swift
This resolves the issue when the incorrect threshold is used to calculate the available space when laying out the cells on OSX. #68
> Return the frame instead of the documentVisibleRect

- Sources/Shared/Core/VerticalBlueprintLayout.swift
Improves handling resizing of windows. If the content size width is different than the new bounds, then the layout will invalidate.
> Compare contentSize.width in shouldInvalidateLayout

- Sources/Shared/Core/BlueprintLayout.swift
#71 This is to make sure that the scrollbar is not overlapping the cells when certain styles are used based on the users preferences.
> OSX - Use collection view frame width instead of the enclosing scroll view

- Sources/Shared/Core/VerticalBlueprintLayout.swift
Fixes #73 - When the collection view has an enclosingScrollView this should be used to calculate the height of which the items should be pinned.
> Update footerY calculations for OSX

- Example-iOS/Scenes/LayoutExampleSceneViewController+VerticalMosaicBlueprintLayout.swift
Shows the basic implementation for headers in the mosaic layout that have been added in #75
> Adding headerReferenceSize to example project.

- Sources/Shared/Core/BlueprintLayout.swift
> Fix item size when the layout is using a horizontal direction in OSX

- Sources/macOS/Extensions/NSCollectionView+Extensions.swift
Fixes #79 when the scrollbar is always visible it overlaps the cells, this will ensure that this doesn't happen.
> Fix document rect so that the scroll bar is correctly positioned in OSX

- Blueprints.xcodeproj/project.pbxproj
- Example-OSX/AppDelegate.swift
- Example-OSX/Example_OSX.entitlements
- Sources/Shared/Core/BlueprintLayout.swift
- Sources/macOS/Extensions/BlueprintLayout+macOS.swift
This adds a "horrible" hack to get the content size to update on macOS when transitioning between layouts. It will temporarily resize the window to make sure that the scroll view's document view gets a new size.
Fixes #87
- Enables `InjectionIII` for the macOS demo
> Fix content size issue on macOS

- Sources/Shared/Core/HorizontalBlueprintLayout.swift
Size is incorrect as it add's additional height for each item per columns, as the section insets are added multiple times.
> Fix content size calculations

- Sources/Shared/Core/VerticalBlueprintLayout.swift
as the previous item may not be the current max, depending on the dynamic heights and number of rows.
> Check the current frame against the existing section max y

- Sources/Shared/Core/BlueprintLayout.swift
This PR fixes a minor issue when using sticky headers in a horizontal collection view in combination with section insets. Now the headers should appear truly sticky instead of adjusting as the user scrolls.
> Properly adjust the headers x origin when using section insets

- Sources/Shared/Core/BlueprintLayout.swift
This fixes a minor misplacement issue of the header when the content size is less than the collection views width. In that case, we shouldn't modify the x coordinate of the stick header or footer.
> Only adjust origin-x if content size is larger than the collection views width

- Blueprints.podspec
- Sources/Shared/Core/BlueprintLayout.swift
- Sources/macOS/Extensions/BlueprintLayout+macOS.swift
- 💻 Empty collection view layouts now receive a content size height of zero on macOS.
> Fix setting content size on empty layouts on macOS

- Blueprints.podspec
- Sources/Shared/Core/BlueprintLayout.swift
Removes the previous fixes that was suppose to align the headers and footers
correctly when reaching the end of a collection view. It appears that the
previous fix was faulty and is now removed.
> Fix header & footer x origin when reaching the end

- Example-OSX/AppDelegate.swift
- Example-iOS/AppDelegate.swift
- Sources/Shared/Core/BlueprintLayout.swift
- Sources/Shared/Core/HorizontalBlueprintLayout.swift
- Sources/Shared/Core/VerticalBlueprintLayout.swift
- Sources/Shared/Mosaic/VerticalMosaicBlueprintLayout.swift
- Tests/Shared/VerticalBlueprintLayoutTests.swift
This implements the delegate methods for header/footer reference sizes so they can be provided just like we do for the items.
This will allow users to provide dynamic heights for headers and footers if they wish.
> Implement delegate methods for header/footer reference size

- Blueprints.podspec
- Sources/Shared/Core/BlueprintLayout.swift
- Tests/iOS+tvOS/HorizontalBlueprintLayoutTests+iOS+tvOS.swift
- Tests/iOS+tvOS/VerticalBlueprintLayoutTests+iOS+tvOS.swift
- Tests/macOS/HorizontalBlueprintLayoutTests+macOS.swift
- Tests/macOS/VerticalBlueprintLayoutTests+macOS.swift
- Set default padding to 1 if `itemsPerRow` is not set
- Add additional padding to the visible rectangle to avoid rare rendering issues with larger collections
> Refactor layoutAttributesForElements to fix rare rendering glitches

- Sources/Shared/Core/BinarySearch.swift
- Sources/Shared/Core/BlueprintLayout.swift
- Tests/iOS+tvOS/HorizontalBlueprintLayoutTests+iOS+tvOS.swift
- Tests/iOS+tvOS/VerticalBlueprintLayoutTests+iOS+tvOS.swift
- Tests/macOS/HorizontalBlueprintLayoutTests+macOS.swift
- Tests/macOS/VerticalBlueprintLayoutTests+macOS.swift
This PR refactors the binary search algorithm to get rid of the `padding` property that shouldn't be necessary in the first place.
> Optimize binary search algorithm

- Sources/Shared/Core/BinarySearch.swift
- Sources/Shared/Core/BlueprintLayout.swift
Simplify the code path of `resolveSizeForItem` to reduce the amount of optional unwrapping
> Refactor `resolveSizeForItem`

- Sources/Shared/Core/BlueprintInvalidationContext.swift
Improve customization by making BlueprintInvalidationContext open
and its methods open.
> Make BlueprintInvalidationContext open

- Package.swift
This PR adds the ability to installs Blueprints as a Swift Package on iOS/tvOS. Due to project structure macOS is not yet supported.
> Swift Package Manager support for iOS
